### ISSUE TITLE
My boot config.txt doesn't have # Boot device section

### ISSUE THREAD

**Issue by yjizhang** [raspberry-vanilla/android_local_manifest#114] opened 2024-08-12 06:16 UTC
Hi, I download the aosp Android 14 code, and build successfully.
But after burn the image to sdcard/usb storage/nvme, there is no # Boot device section in /boot/config.txt.

**Comment by KonstaT** [comment] 2024-08-12 09:10
There isn't supposed to be.

Closing as a duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/113.

**Closed as completed by KonstaT** 2024-08-12 09:10 UTC
