### ISSUE TITLE
Android Automotive build does not show Settings -> System -> Raspberry Pi settings 

### ISSUE THREAD

**Issue by abhilashdeshmukh** [raspberry-vanilla/android_local_manifest#50] opened 2023-12-04 23:00 UTC
After building AAOS 13, it does not show "Raspberry Pi settings" submenu in settings. Hence, advance settings like overclocking, rebooting into recovery, power buttons are not accessible. How it can be enabled for AAOS build? How it comes when one build tablet build?

**Comment by KonstaT** [comment] 2023-12-05 10:11
Duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/35.

**Closed as completed by KonstaT** 2023-12-05 10:11 UTC
