### ISSUE TITLE
USB boot option does not work

### ISSUE THREAD

**Issue by lohriialo** [raspberry-vanilla/android_local_manifest#143] opened 2024-10-26 07:19 UTC
I've built for Pi 5 using the following commands
```
. build/envsetup.sh
lunch aosp_rpi5-ap3a-userdebug
make bootimage systemimage vendorimage -j$(nproc)
./rpi5-mkimg.sh
```
after writing it to a USB thumb drive, added the following to config.txt
```
#dtoverlay=android-sdcard
dtoverlay=android-usb
#dtoverlay=android-nvme
```
And I can also see the overlay `android-usb.dtbo` in `/boot`
But USB boot is not working, it boot loops

I had to rebuilt vendor.img by editing `/device/brcm/rpi5/ramdisk/fstab.rpi5` to
```
/dev/block/sda2
/dev/block/sda3
/dev/block/sda4
```
Is this expected or does the default build of `fstab.rpi5` should respect `dtoverlay=android-usb` in `config.txt`?

**Comment by KonstaT** [comment] 2024-10-26 08:32
Duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/113 & https://github.com/raspberry-vanilla/android_local_manifest/issues/114.

You would follow the project's documentation on the relevant wik pagei.
https://github.com/raspberry-vanilla/android_local_manifest/wiki/USB-boot

**Closed as completed by KonstaT** 2024-10-26 08:32 UTC
