### ISSUE TITLE
error: "libgbm_mesa_wrapper (SHARED_LIBRARIES android-arm) missing libgbm_mesa (SHARED_LIBRARIES android-arm)"

### ISSUE THREAD

**Issue by YogeshPethuram** [raspberry-vanilla/android_local_manifest#68] opened 2024-03-21 12:05 UTC
Hello @KonstaT ,
Recently I have tried building this [android_local_manifest - Branch android-14.0 ](https://github.com/raspberry-vanilla/android_local_manifest/tree/android-14.0)
I have followed the step by step procedure given [here](https://github.com/raspberry-vanilla/android_local_manifest/blob/android-14.0/README.md)

Initially I have received the below error:

```
error: libcrypto's ABI has EXTENDING CHANGES. Please check compatibility report at: out/soong/.intermediates/external/boringssl/libcrypto/android_vendor.34_arm64_armv8-a_cortex-a72_shared/libcrypto.so.ab
idiff
error: Please update ABI references with: $ANDROID_BUILD_TOP/development/vndk/tools/header-checker/utils/create_reference_dumps.py -l libcrypto
16:34:43 ninja failed with: exit status 1
```

After that I have executed this 

> $ANDROID_BUILD_TOP/development/vndk/tools/header-checker/utils/create_reference_dumps.py -l libcrypto

 as it is given there.

after executing that command , I have received another error , which I have mentioned below 

```
FAILED: 
external/minigbm/gbm_mesa_driver/Android.mk: error: "libgbm_mesa_wrapper (SHARED_LIBRARIES android-arm) missing libgbm_mesa (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:1135: error: exiting from previous errors.
16:39:28 ckati failed with: exit status 1
Traceback (most recent call last):
  File "/home/yogesh/AOSP_14_Rpi/development/vndk/tools/header-checker/utils/create_reference_dumps.py", line 228, in <module>
    main()
  File "/home/yogesh/AOSP_14_Rpi/development/vndk/tools/header-checker/utils/create_reference_dumps.py", line 219, in main
    num_processed = create_source_abi_reference_dumps_for_all_products(args)
  File "/home/yogesh/AOSP_14_Rpi/development/vndk/tools/header-checker/utils/create_reference_dumps.py", line 146, in create_source_abi_reference_dumps_for_all_products
    make_libs_for_product(args.libs, product, args.build_variant,
  File "/home/yogesh/AOSP_14_Rpi/development/vndk/tools/header-checker/utils/create_reference_dumps.py", line 52, in make_libs_for_product
    make_libraries(product, variant, vndk_version, targets, libs,
  File "/home/yogesh/AOSP_14_Rpi/development/vndk/tools/header-checker/utils/utils.py", line 168, in make_libraries
    lsdump_paths = read_lsdump_paths(product, variant, vndk_version, targets,
  File "/home/yogesh/AOSP_14_Rpi/development/vndk/tools/header-checker/utils/utils.py", line 264, in read_lsdump_paths
    make_targets(product, variant, [lsdump_paths_file_path])
  File "/home/yogesh/AOSP_14_Rpi/development/vndk/tools/header-checker/utils/utils.py", line 157, in make_targets
    subprocess.check_call(make_cmd, cwd=AOSP_DIR)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['build/soong/soong_ui.bash', '--make-mode', '-j', 'TARGET_PRODUCT=aosp_arm', 'TARGET_BUILD_VARIANT=userdebug', 'out/target/product/generic/lsdump_paths.txt']' returned non-zero exit status 1.
```

Even though I have followed the links which I got from the [previously closed issue](https://github.com/raspberry-vanilla/android_local_manifest/issues/63) , build is not getting Success.

Please try to update the branch android-14.0 if any changes required for solving this issue.

**Comment by KonstaT** [comment] 2024-03-22 17:01
Still a duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/63 that can be used for discussion. No need to open a separate issue.

I don't have anything new to add. Most likely some issue with your build environment that is not something that can be addressed in AOSP source/Raspberry Vanilla project.

**Closed as completed by KonstaT** 2024-03-22 17:01 UTC
