### ISSUE TITLE
Error while making the ota using make dist on AOSP13

### ISSUE THREAD

**Issue by unisubzee** [raspberry-vanilla/android_local_manifest#75] opened 2024-04-15 09:09 UTC
for AOSP13, when running `make dist` command to create an ota.zip file I get the following error:

```
make VERBOSE=1  dist -j1
[W][2024-04-15T08:59:25+0000][11846] logParams():267 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2024-04-15T08:59:25+0000][11846] logParams():277 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
build/make/core/soong_config.mk:209: warning: BOARD_PLAT_PUBLIC_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS instead.
build/make/core/soong_config.mk:210: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=13
TARGET_PRODUCT=aosp_rpi4
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a72
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a72
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-150-generic-x86_64-Ubuntu-22.04.4-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=TQ3A.230901.001
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/brcm/rpi4 vendor/brcm/rpi4 external/v4l2_codec2
============================================
[W][2024-04-15T08:59:25+0000][11890] logParams():267 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2024-04-15T08:59:25+0000][11890] logParams():277 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[W][2024-04-15T08:59:25+0000][11924] logParams():267 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2024-04-15T08:59:25+0000][11924] logParams():277 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[W][2024-04-15T08:59:26+0000][11954] logParams():267 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2024-04-15T08:59:26+0000][11954] logParams():277 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[W][2024-04-15T08:59:26+0000][12126] logParams():267 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2024-04-15T08:59:26+0000][12126] logParams():277 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[W][2024-04-15T08:59:26+0000][12130] logParams():267 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2024-04-15T08:59:26+0000][12130] logParams():277 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[  0% 1/4644] build out/target/product/rpi4/host_init_verifier_output.txt
FAILED: out/target/product/rpi4/host_init_verifier_output.txt
/bin/bash -c "out/host/linux-x86/bin/host_init_verifier 		-p out/target/product/rpi4/obj/ETC/passwd_system_intermediates/passwd_system 		-p out/target/product/rpi4/obj/ETC/passwd_system_ext_intermediates/passwd_system_ext 		-p out/target/product/rpi4/obj/ETC/passwd_vendor_intermediates/passwd_vendor 		-p out/target/product/rpi4/obj/ETC/passwd_odm_intermediates/passwd_odm 		-p out/target/product/rpi4/obj/ETC/passwd_product_intermediates/passwd_product 		--property-contexts=out/target/product/rpi4/obj/ETC/plat_property_contexts_intermediates/plat_property_contexts 		--property-contexts=out/target/product/rpi4/obj/ETC/system_ext_property_contexts_intermediates/system_ext_property_contexts 		--property-contexts=out/target/product/rpi4/obj/ETC/product_property_contexts_intermediates/product_property_contexts 		--property-contexts=out/target/product/rpi4/obj/ETC/vendor_property_contexts_intermediates/vendor_property_contexts 		--property-contexts=out/target/product/rpi4/obj/ETC/odm_property_contexts_intermediates/odm_property_contexts 		--out_system out/target/product/rpi4/system 		--out_system_ext out/target/product/rpi4/system/system_ext 		--out_vendor out/target/product/rpi4/vendor 		--out_odm out/target/product/rpi4/vendor/odm 		--out_product out/target/product/rpi4/system/product 		> out/target/product/rpi4/host_init_verifier_output.txt"
host_init_verifier: out/target/product/rpi4/vendor/etc/init/android.hardware.media.c2@1.0-service-v4l2-64.rc: 1: ignored duplicate definition of service 'android-hardware-media-c2-v4l2-hal-1-0'
host_init_verifier: Failed to parse init scripts with 1 error(s).
08:59:40 ninja failed with: exit status 1
```

**Comment by KonstaT** [comment] 2024-04-15 18:14
Duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/69.

**Closed as completed by KonstaT** 2024-04-15 18:14 UTC
