### ISSUE TITLE
Failed to build aosp_rpi5_car-ap2a-userdebug

### ISSUE THREAD

**Issue by ullnorse** [raspberry-vanilla/android_local_manifest#105] opened 2024-07-02 13:47 UTC
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=14
PRODUCT_INCLUDE_TAGS=com.android.mainline mainline_module_prebuilt_nightly
TARGET_PRODUCT=aosp_rpi5_car
TARGET_BUILD_VARIANT=userdebug
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a76
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_OS=linux
HOST_CROSS_OS=windows
BUILD_ID=AP2A.240605.024
OUT_DIR=out
============================================
FAILED: ninja: 'Android.bp', needed by 'out/soong/build.aosp_rpi5_car.ninja', missing and no known rule to make it
13:55:46 soong bootstrap failed with: exit status 1

#### failed to build some targets (1 seconds) ####

**Comment by KonstaT** [comment] 2024-07-02 20:36
Duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/104.
Fixed by https://github.com/raspberry-vanilla/android_local_manifest/commit/6ae8acffbde1b487a7a3db792753ce5afcf17328.

**Closed as completed by KonstaT** 2024-07-02 20:36 UTC
