### ISSUE TITLE
No Pi-related settings in AOSP 14 for Pi 5

### ISSUE THREAD

**Issue by RankoR** [raspberry-vanilla/android_local_manifest#119] opened 2024-09-01 21:25 UTC
I've installed the prebuilt version and there was a Pi-related settings .

After that I've built the current version:

```
lunch aosp_rpi5-ap2a-userdebug
make bootimage systemimage vendorimage -j24
./rpi5-mkimg.sh
```

It builds and runs, however, there is no Pi settings anymore.

As I can see, they should be included:

```
# Overlays
PRODUCT_PACKAGES += \
    AndroidRpiOverlay \
    SettingsRpiOverlay \
    SettingsProviderRpiOverlay \
    SystemUIRpiOverlay \
    WifiRpiOverlay
```

Another interesting thing is that I'm also including my own prebuilt apk (in `rpi5/device.mk`), and it's not installed in the built version as well, while I see it in `out/target/product/rpi5/vendor/priv-app` (but works fine for the emulator for example).

**Comment by RankoR** [comment] 2024-09-02 21:20
Just checked on Pi 4 on the same source tree - same result.

Any ideas on how to debug this?

**Comment by KonstaT** [comment] 2024-09-03 13:01
Duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/35.

**Closed as completed by KonstaT** 2024-09-03 13:01 UTC
