### ISSUE TITLE
the image for andraoid 14(raspberrypi-4) booting problem

### ISSUE THREAD

**Issue by devalapalli** [raspberry-vanilla/android_local_manifest#86] opened 2024-05-10 05:38 UTC
Hello @KonstaT ,
 ##
We tried booting android 14 of rpi4_car ,from source code from a below mentioned link
(https://github.com/raspberry-vanilla/android_local_manifest/tree/android-14.0)
we are tried booting this from sdcard but its not going and the logs are repeated .
this error is appeared -
cutils-trace: Error opening trace file: No such file or director.

Environment:

Android version: 14
Board : raspberry pi 4
Booting mode : Sdcard

Please check the  attached logs.
android_14_rpi4_car 
 #[aosp14_rp4_sd.txt](
https://github.com/raspberry-vanilla/android_local_manifest/files/15270661/aosp14_rp4_sd.txt)

please let me know if you need any information.

Thanks

**Comment by KonstaT** [comment] 2024-05-10 09:32
As mentioned in https://github.com/raspberry-vanilla/android_local_manifest/issues/85 you would need to provide `logcat` output.

AOSP14 QPR2 Android Automotive is not currently booting to the UI in any so closing as a duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/83.

**Closed as completed by KonstaT** 2024-05-10 09:32 UTC
