### ISSUE TITLE
Build aosp_rpi5_car with manifest version: android-14.0.0_r22 fails

### ISSUE THREAD

**Issue by Tobamalau** [raspberry-vanilla/android_local_manifest#161] opened 2024-12-16 14:28 UTC
Build as described in README.

Log:

```
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=14
PRODUCT_INCLUDE_TAGS=com.android.mainline
TARGET_PRODUCT=aosp_rpi5_car
TARGET_BUILD_VARIANT=userdebug
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a76
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.15.0-107-generic-x86_64-Ubuntu-20.04.6-LTS
HOST_CROSS_OS=windows
BUILD_ID=UQ1A.240205.002
OUT_DIR=out
```

`[ 99% 413/414] analyzing Android.bp files and generating ninja file at out/soong/build.ninja
FAILED: out/soong/build.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out" 
    -o out/soong/build.ninja --bazel-mode --globListDir build --globFile out/soong/globs-build.ninja -t -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/s
oong/soong.environment.used.build Android.bp
error: external/drm_hwcomposer/Android.bp:271:1: "com.android.hardware.graphics.composer.drm_hwcomposer" depends on undefined module "com.android.hardware.key".
Or did you mean ["com.android.hardware.usb"]?
error: external/drm_hwcomposer/Android.bp:271:1: "com.android.hardware.graphics.composer.drm_hwcomposer" depends on undefined module "com.android.hardware.certificate".
Or did you mean ["com.android.hardware.usb.certificate" "libcom.android.sysprop.bluetooth"]?
11:40:46 soong bootstrap failed with: exit status 1`

most recent external/drm_hwcomposer doesn't fit to r22.

drm_hwcomposer needs a dedicated branch or tag for r22.

**Comment by KonstaT** [comment] 2024-12-16 14:31
Duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/160.

**Closed as completed by KonstaT** 2024-12-16 14:31 UTC
