### ISSUE TITLE
Remount not working

### ISSUE THREAD

**Issue by alvenan** [raspberry-vanilla/android_local_manifest#126] opened 2024-09-12 20:14 UTC
Even after running `adb root`, remounting doesn't work.
```
$ adb shell getprop ro.build.flavor
aosp_rpi4-userdebug
$ adb remount
Device must be bootloader unlocked
$ adb shell
rpi4:/ # remount
Device must be bootloader unlocked
1|rpi4:/ # remount /
Device must be bootloader unlocked
1|rpi4:/ # remount /system
Device must be bootloader unlocked
1|rpi4:/ # remount /vendor
Device must be bootloader unlocked
```
This can impact the command `adb sync` and any push of file to system/vendor partitions, and it is necessary to reflash the SD card after every change. 
Is there a command or modification in source that can resolve this issue?

Thanks!
Álison Venâncio

**Comment by KonstaT** [comment] 2024-09-13 08:38
Duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/47.

In rooted shell you can:
```
mount -o rw,remount /
mount -o rw,remount /vendor
```

**Closed as completed by KonstaT** 2024-09-13 08:38 UTC
