### ISSUE TITLE
Gps is not enabled: enable location services to determine your location

### ISSUE THREAD

**Issue by rania-taabouri** [raspberry-vanilla/android_local_manifest#125] opened 2024-09-11 16:05 UTC
I’m currently working on a custom Android 13 ROM for a Raspberry Pi 4, and I'm encountering issues with enabling GPS functionality. the gps works correctly i gave right permissions to the app which is SygicGPSNavigation i tried to manually activate the gps provider with this command 
`adb shell settings put secure location_providers_allowed +gps`

but the application still says gps not enabled 
even tried with waze it says no gps connection don't know why apps are not detecting the gps 
this might help
```
$ adb logcat | grep -i gps
09-11 15:36:59.801 19678 19893 E TrafficDataSDK: LocationManager requestLocationUpdates(): provider "gps" does not exist
09-11 15:36:59.801 19678 19893 E TrafficDataSDK: java.lang.IllegalArgumentException: provider "gps" does not exist
```

**Comment by KonstaT** [comment] 2024-09-11 17:17
Raspberry Pi doesn't have any built-in GPS hardware and Raspberry Vanilla project doesn't provide support for any external GPS hardware.

Duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/42.

**Closed as completed by KonstaT** 2024-09-11 17:17 UTC
