### ISSUE TITLE
 Build AAOS branch  android-14.0.0_r50 

### ISSUE THREAD

**Issue by pino-kim** [raspberry-vanilla/android_local_manifest#108] opened 2024-07-03 03:11 UTC
## Description
* Build AAOS branch  `android-14.0.0_r50`  

## Type command
```
. build/envsetup.sh
lunch aosp_rpi4_car-ap2a-userdebug
```

## Log
```
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=14
PRODUCT_INCLUDE_TAGS=com.android.mainline mainline_module_prebuilt_nightly
TARGET_PRODUCT=aosp_rpi4_car
TARGET_BUILD_VARIANT=userdebug
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.5.0-41-generic-x86_64-Ubuntu-22.04.4-LTS
HOST_CROSS_OS=windows
BUILD_ID=AP2A.240605.024
OUT_DIR=out
============================================
FAILED: ninja: 'Android.bp', needed by 'out/soong/build.aosp_rpi4_car.ninja', missing and no known rule to make it
17:22:05 soong bootstrap failed with: exit status 1

#### failed to build some targets (44 seconds) ####
```

Dear @KonstaT 
Can you help me or hint to  solve this issue?
I previously succeeded by building aosp13 in this project.

**Comment by KonstaT** [comment] 2024-07-03 09:26
Duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/104 and already resolved. Update the local manifest and `repo sync`.

**Closed as completed by KonstaT** 2024-07-03 09:26 UTC
