### ISSUE TITLE
Can't access Raspberry Pi Settings in AAOS 14

### ISSUE THREAD

**Issue by DGMeyer96** [raspberry-vanilla/android_local_manifest#138] opened 2024-10-23 01:00 UTC
I built Android Automotive OS 14 R67 using branch [android-14.0](https://github.com/raspberry-vanilla/android_local_manifest/tree/android-14.0) for Raspberry Pi 5 (8GB).  I am trying to enable ADB and Serial Connection.  I've enabled developer mode and when I look for the Raspberry Pi settings menu in Settings -> System, I don't see it.  

For ADB I've clicked on Enable ADB Connection in developer settings but I still don't have an ADB connection.  I've tried using a USB A to A data cable connected directly to the RPi via USB as well as a USB hub with power connected via the USB-C port. 

For Serial I used a Serial to USB connection via the GPIO pins and my laptop detects it on TeraTerm.  I set the Baud Rate to 115200 but I don't get a terminal connection there either.  Is the baud rate different?

**Comment by KonstaT** [comment] 2024-10-23 08:56
Duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/35.

ADB over USB is a duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/88. You would need to use the USB-C port with outside power source. USB-A ports on Pi are host mode only so it is not possible to use ADB on those. I don't recall if Android Automotive has ADB over network option but you can add `persist.adb.tcp.port=5555` to system/vendor properties to enable it.

Serial console is on the dedicated UART connector instead of GPIO14/15. You would need to revert https://github.com/raspberry-vanilla/android_device_brcm_rpi5/commit/71b154a8bb0facac24c8a27a0bfff93d3fe1aaf5 to move it back to GPIO14/15.

**Closed as completed by KonstaT** 2024-10-23 08:56 UTC
